//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoFoton {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeoFoton.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista previa de la actualización automática.
        /// </summary>
        internal static string chkAutoUpdatePreview {
            get {
                return ResourceManager.GetString("chkAutoUpdatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprime las imágenes de todos los directorios hijos (¡ADVERTENCIA! Sobrescribe las imágenes existentes)..
        /// </summary>
        internal static string chkCompressAll {
            get {
                return ResourceManager.GetString("chkCompressAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprimir si el tamaño del archivo es mayor a.
        /// </summary>
        internal static string chkFileSize {
            get {
                return ResourceManager.GetString("chkFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros de compresión.
        /// </summary>
        internal static string grpCompress {
            get {
                return ResourceManager.GetString("grpCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir el directorio para comprimir todas las imágenes.
        /// </summary>
        internal static string grpOpen {
            get {
                return ResourceManager.GetString("grpOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista previa de la compresión.
        /// </summary>
        internal static string grpPicPreview {
            get {
                return ResourceManager.GetString("grpPicPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar las imágenes comprimidas en un directorio (opcional).
        /// </summary>
        internal static string grpSave {
            get {
                return ResourceManager.GetString("grpSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calidad (en %).
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        internal static string languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cambió los parámetros de compresión?.
        /// </summary>
        internal static string lblPreview {
            get {
                return ResourceManager.GetString("lblPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASEGÚRESE DE HABER HECHO UNA COPIA DE SEGURIDAD PRIMERO..
        /// </summary>
        internal static string lblTakeBackup {
            get {
                return ResourceManager.GetString("lblTakeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar como JPEG.
        /// </summary>
        internal static string rbJpeg {
            get {
                return ResourceManager.GetString("rbJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cambiar el tipo (las imágenes RAW se comprimirán como JPEG).
        /// </summary>
        internal static string rbKeepOriginal {
            get {
                return ResourceManager.GetString("rbKeepOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar como PNG.
        /// </summary>
        internal static string rbPng {
            get {
                return ResourceManager.GetString("rbPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho fijo.
        /// </summary>
        internal static string rbSizeInPixels {
            get {
                return ResourceManager.GetString("rbSizeInPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva dimensión en %.
        /// </summary>
        internal static string rbSizePercentage {
            get {
                return ResourceManager.GetString("rbSizePercentage", resourceCulture);
            }
        }
    }
}
